### ISSUE TITLE
Fix "Automated documentation update" script

### ISSUE THREAD

**Issue by JohnRiv** [Comcast/Surf-N-Perf#78]
[Travis is failing to execute deploy.sh:](https://travis-ci.org/github/Comcast/Surf-N-Perf/jobs/737811254)

```
$ test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash deploy.sh
/home/travis/build/Comcast/Surf-N-Perf/node_modules/chalk/source/index.js:106
	...styles,
	^^^
SyntaxError: Unexpected token ...
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:549:28)
    at Object.Module._extensions..js (module.js:586:10)
    at Module.load (module.js:494:32)
    at tryModuleLoad (module.js:453:12)
    at Function.Module._load (module.js:445:3)
    at Module.require (module.js:504:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/travis/build/Comcast/Surf-N-Perf/node_modules/grunt-legacy-log-utils/index.js:12:13)
```

I'm guessing updating Node and/or using package-lock.json will address this

**Comment by JohnRiv** [comment]
Hopefully https://travis-ci.org/github/Comcast/Surf-N-Perf/builds/739022336 results in a fresh "Automated documentation update" commit to the `gh-pages` branch... if not we'll reopen
